feat(96): init and create commend
statoscope/statoscope pull request #139
Opened 2021-11-01 20:20 UTC by OrlovAlexei

- feat(cli): added create and init rule # Please, use semantic commit message: # type(scope): message # or # type: message # # Types are: # - build - code build changes (webpack config, etc) # - ci - CI changes (GitHub actions, CI scripts) # - docs - documentation changes # - feat - new features # - fix - bug fixes # - perf - performance improvements # - refactor - code refactoring (also types changes) # - style - code style changes (also eslint/prettier config changes) # - test - add/fix/remove tests, or change jest configuration # - chore - everything else # # The scope is a package name that changes related to # # For example: # test(cli): add foo command # or # docs: fix root readme typos
- fix(webpack-model): added initial field in type Chunk # Please, use semantic commit message: # type(scope): message # or # type: message # # Types are: # - build - code build changes (webpack config, etc) # - ci - CI changes (GitHub actions, CI scripts) # - docs - documentation changes # - feat - new features # - fix - bug fixes # - perf - performance improvements # - refactor - code refactoring (also types changes) # - style - code style changes (also eslint/prettier config changes) # - test - add/fix/remove tests, or change jest configuration # - chore - everything else # # The scope is a package name that changes related to # # For example: # test(cli): add foo command # or # docs: fix root readme typos
- feat(cli): added init command # Please, use semantic commit message: # type(scope): message # or # type: message # # Types are: # - build - code build changes (webpack config, etc) # - ci - CI changes (GitHub actions, CI scripts) # - docs - documentation changes # - feat - new features # - fix - bug fixes # - perf - performance improvements # - refactor - code refactoring (also types changes) # - style - code style changes (also eslint/prettier config changes) # - test - add/fix/remove tests, or change jest configuration # - chore - everything else # # The scope is a package name that changes related to # # For example: # test(cli): add foo command # or # docs: fix root readme typos
- feat(cli): added create command # Please, use semantic commit message: # type(scope): message # or # type: message # # Types are: # - build - code build changes (webpack config, etc) # - ci - CI changes (GitHub actions, CI scripts) # - docs - documentation changes # - feat - new features # - fix - bug fixes # - perf - performance improvements # - refactor - code refactoring (also types changes) # - style - code style changes (also eslint/prettier config changes) # - test - add/fix/remove tests, or change jest configuration # - chore - everything else # # The scope is a package name that changes related to # # For example: # test(cli): add foo command # or # docs: fix root readme typos

2021-11-01 21:19 UTC, smelukov requested changes
Really thanks for the PR!
Please look at some comments above ☺️

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/reporter.ts
> +  async run(result){
```suggestion
  async run(result) {
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/reporter.ts
> +  constructor(){}
```suggestion
  constructor() {}
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/plugin.ts
> +export const asyncChunkRulePluginTs = `import type{ PluginFn } from '@statoscope/stats-validator/dist/plugin';
```suggestion
export const asyncChunkRulePluginTs = `import type { PluginFn } from '@statoscope/stats-validator/dist/plugin';
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/plugin.ts
> +import type{ Rule } from '@statoscope/stats-validator/dist/rule';
```suggestion
import type { Rule } from '@statoscope/stats-validator/dist/rule';
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/plugin.ts
> +import type{ Prepared } from '@statoscope/webpack-model';
```suggestion
import type { Prepared } from '@statoscope/webpack-model';
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/plugin.ts
> +      'async-chunk': asyncChunkRule,
let's add some dummy-import for this

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/index.ts
> +      export: true,
seems like we can replace `import/export` with `module: 'commonjs'/'esm'`

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/templates/index.ts
> +    return mapper.rule(fileExt, {
I think that template function might be described as:
```ts
type TemplateOptions = {
  output: {
    type: 'js' | 'ts',
    module: 'commonjs' | 'esm',
  }
};
type Template<TAdditionalOptions> = (TemplateOptions, TAdditionalOptions) => string;
// TAdditionalOptions - is template-specific options, might be passed from cli args
```

Example:
```ts
const asyncChunkRuleTs: Template<unknown> = (options): string => options.output.type === 'ts' ? `...` : `...`
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/create.ts
> +default usage: create rule
```suggestion
create rule # create example-rule from the template
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/create.ts
> +Custom path: create plugin --output path/to/folder
```suggestion
create plugin --output path/to/folder # create example-plugin from the template and save it into a specific directory
```

2021-11-01 21:19 UTC, smelukov commented on packages/cli/src/commands/create.ts
> +File ext: create rule --ext ts`,
```suggestion
create rule --ext ts # create example-rule from the template and save it as typescript source`,
```

2021-11-05 14:43 UTC, OrlovAlexei commented
@smelukov  Hello, thank you for the suggestion! I added support for ```esm``` and ```commonjs``` modules for JS files. I only added a comment about ``` jora-queries ``` because it only returns the ``` unknown ``` type. Maybe there is a task to fix this?

2021-11-09 05:57 UTC, smelukov commented
@OrlovAlexei are you done here?

2021-11-10 20:44 UTC, OrlovAlexei commented
@smelukov yes, I'm done

2021-11-25 17:10 UTC, merged

2021-11-25 17:11 UTC, smelukov commented
Thank!
Sorry for so long waiting.
I've got some rest )